apiVersion: v1
kind: LimitRange
metadata:
  name: cloverai-limit-range
  namespace: cloverai
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
      