# Global settings
global:
  scrape_interval: 15s     # Default scrape interval
  evaluation_interval: 15s # Evaluation interval for rules
  scrape_timeout: 10s     # Timeout for scrape requests

# Rule files for alerting
rule_files:
  - "rules/bias_alerts.yml"
  - "rules/privacy_alerts.yml"
  - "rules/governance_alerts.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

# Scrape configurations
scrape_configs:
  # AI Model Metrics
  - job_name: 'cloverai-model-metrics'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [model_version]
        target_label: version
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app

  # Bias Detection Metrics
  - job_name: 'bias-detection'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics/bias'
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [protected_attribute]
        target_label: attribute_type

  # Privacy Protection Metrics
  - job_name: 'privacy-protection'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics/privacy'
    scrape_interval: 1m
    metric_relabel_configs:
      - source_labels: [encryption_type]
        target_label: protection_method

  # Governance Automation Metrics
  - job_name: 'governance-automation'
    static_configs:
      - targets: ['localhost:8003']
    metrics_path: '/metrics/governance'
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: [policy_type]
        target_label: governance_area

  # Kubernetes Metrics
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app

  # Node Exporter Metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

# Custom metric configurations
custom_metrics:
  # Bias Detection Metrics
  - name: ai_model_bias_score
    type: gauge
    description: "Bias score for protected attributes"
    labels:
      - model_name
      - protected_attribute
      - dataset_version

  # Privacy Metrics
  - name: data_encryption_status
    type: gauge
    description: "Encryption status of sensitive data"
    labels:
      - data_type
      - encryption_method

  # Governance Metrics
  - name: policy_compliance_score
    type: gauge
    description: "Overall policy compliance score"
    labels:
      - policy_type
      - namespace

  # Performance Metrics
  - name: model_inference_latency
    type: histogram
    description: "Model inference latency in seconds"
    buckets: [0.1, 0.5, 1.0, 2.0, 5.0]

  # Resource Usage
  - name: gpu_memory_usage
    type: gauge
    description: "GPU memory usage by AI models"
    labels:
      - gpu_id
      - model_name

# Recording rules for derived metrics
recording_rules:
  groups:
    - name: ai_governance_metrics
      rules:
        - record: job:bias_detection_rate:avg_5m
          expr: rate(ai_model_bias_score[5m])
        
        - record: job:privacy_violation_rate:avg_5m
          expr: rate(privacy_violation_total[5m])
        
        - record: job:governance_compliance_rate:avg_5m
          expr: rate(policy_compliance_score[5m])

# Alerting rules
alerting_rules:
  groups:
    - name: bias_alerts
      rules:
        - alert: HighBiasScore
          expr: ai_model_bias_score > 0.2
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High bias detected in model"
            
    - name: privacy_alerts
      rules:
        - alert: PrivacyViolation
          expr: data_encryption_status < 1
          for: 1m
          labels:
            severity: critical
            
    - name: governance_alerts
      rules:
        - alert: PolicyNonCompliance
          expr: policy_compliance_score < 0.9
          for: 15m
          labels:
            severity: warning
            