apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloverai-compute-resources
  namespace: cloverai
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    requests.nvidia.com/gpu: "1"
